<?php
header('Content-type: application/pdf');

$spec = array(
    'pageSize' => 'A4',
    'columns' => 5,
    'margins' => array(
        'top' => 10.7,
        'bottom' => 10.7,
        'left' => 5.75,
        'right' => 5.75
    ),
    'padding' => array(
        'horizontal' => 2,
        'vertical' => 0
    ),
    'labels' => array(
        'height' => 21.2,
        'width' => 38.1
    ),
    'fontSize' => 8
    
);

$data = array(
    "Mr Jones\n 12 This Street\nHellotown"
);

echo $this->labels($spec, $data);